Controllers/CompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Dominio.Entidades;
using Repositorios;

namespace WebAPI.Controllers
{
    [RoutePrefix("api/compras")]
    public class CompraController : ApiController
    {
        RepositorioCompra repocompra = new RepositorioCompra();
        RepositorioPrestadorSalud repoprestador = new RepositorioPrestadorSalud();

        [HttpGet]
        public IHttpActionResult Get(int id)
        {
            var comp = repocompra.FindById(id);
            return Ok(comp);
        }

        [HttpPost]
        [Route("")]
        public IHttpActionResult Post([FromBody] Compra c)
        {
            repocompra.Add(c);
            return Created("~/api/compras/" + c.Id, c);
        }

    }
}

Controllers/VacunasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Repositorios;

namespace WebAPI.Controllers
{
    [RoutePrefix("api/vacunas")]
    public class VacunasController : ApiController
    {
        RepositorioVacuna repovacuna = new RepositorioVacuna();

        [Route("filtradas")]
        [HttpGet]
        public IHttpActionResult FiltrarVacunas(int? fase, int? rangomin, int? rangomax, string tipo, string laboratorio, string pais)
        {
            try
            {
                if(fase == null && rangomin == null && rangomax == null && tipo == null && laboratorio == null && pais == null)
                {
                    var vacunas = repovacuna.FindAll();
                    return Ok(vacunas);
                }
                else
                {
                    var vacunas = repovacuna.FiltrarVacunas(fase, rangomin, rangomax, tipo, laboratorio, pais);
                    return Ok(vacunas);
                }
            }
            catch (Exception ex)
            {
                return InternalServerError
                (new Exception("No es posible filtrar las vacunas",
                ex.InnerException));
            }
        }

        [Route("filtradasunion")]
        [HttpGet]
        public IHttpActionResult FiltrarVacunasUnion(int? fase, int? rangomin, int? rangomax, string tipo, string laboratorio, string pais)
        {
            try
            {
                if (fase == null && rangomin == null && rangomax == null && tipo == null && laboratorio == null && pais == null)
                {
                    var vacunas = repovacuna.FindAll();
                    return Ok(vacunas);
                }
                else
                {
                    var vacunas = repovacuna.FiltrarVacunasUnion(fase, rangomin, rangomax, tipo, laboratorio, pais);
                    return Ok(vacunas);
                }
            }
            catch (Exception ex)
            {
                return InternalServerError
                (new Exception("No es posible filtrar las vacunas",
                ex.InnerException));
            }
        }
    }
}

Views/Vacunas/Filter.cshtml

@{
    ViewBag.Title = "Filtro";
}

<h2>Filtrar Vacunas</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        <h4>Filtrar Por:</h4>

        <div class="form-group">
            <label class="control-label col-md-2">Fase</label>
            <div class="col-md-10">
                <input type="number" id="fase" name="fase" class="form-control" />
            </div>
        </div>
        <div>
            <div class="form-group">
                <label class="control-label col-md-2">Rango Precio Minimo</label>
                <div class="col-md-6">
                    <input type="number" id="rangomin" name="rangomin" class="form-control" />
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Rango Precio Máximo</label>
                <div class="col-md-6">
                    <input type="number" id="rangomax" name="rangomax" class="form-control" />
                </div>
            </div>
            <p>Para filtrar por precio debe completar ambos campos.</p>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Tipo de Vacuna</label>
            <div class="col-md-6">
                <input type="text" id="tipo" name="tipo" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Laboratorio</label>
            <div class="col-md-10">
                <input type="text" id="laboratorio" name="laboratorio" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Pais</label>
            <div class="col-md-10">
                <input type="text" id="pais" name="pais" class="form-control" />
            </div>
        </div>

        <label class="form-check-label">Seleccione Filtro</label>
        <select id="select" name="select" class="form-select">
            <option selected>Opciones</option>
            <option value="interseccion">Por Intersección</option>
            <option value="union">Por Unión</option>
        </select>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Filtrar" class="btn btn-default" />
            </div>
        </div>
        @ViewBag.error
    </div>
}


@if (ViewBag.lista != null)
{
    <table class="table">
        <tr>
            <th>
                @Html.Label("Nombre")
            </th>
            <th>
                @Html.Label("Tipo de vacuna")
            </th>
            <th>
                @Html.Label("Precio")
            </th>
            <th>

            </th>
        </tr>

        @foreach (Dominio.Entidades.Vacuna vac in ViewBag.lista)
        {
            <tr>
                <td>
                    @Html.DisplayName(vac.Nombre)
                </td>
                <td>
                    @Html.DisplayName(vac.VacunaTipo)
                </td>
                <td>
                    @Html.DisplayName(vac.Precio.ToString())
                </td>
                <td>
                    @Html.ActionLink("Comprar", "Index","Compra", new { nombre = vac.Nombre }, null)
                </td>
            </tr>
        }

    </table>
}

<div>
    @Html.ActionLink("Volver", "Index")
</div>